substitutions:
  #komunikační piny, pokud používáte originální desku Siton WiFi modulu, nic neměňte
  rxPin: D1
  txPin: D2
  node_name: "Siton210" #název zařízení
  updates: 10s #četnost aktualizací
  adresa: "12" #ID meniče/adresa. Výchozí adresa Sitonu je 12 (0x0C)
  
esphome:
  name: siton210

esp8266:
  board: nodemcuv2

# Enable logging
logger:
    #level: VERY_VERBOSE
    #level: VERBOSE
    #baud_rate: 0

# Enable Home Assistant API
api:
  encryption:
    #POUŽIJTE VLASTNÍ VYGENEROVANÝ KLÍČ
    key: ""

ota:
  #POUŽIJTE VLASTNÍ VYGENEROVANÉ HESLO
  password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${node_name} Fallback Hotspot"
    #POUŽIJTE VLASTNÍ VYGENEROVANÉ HESLO
    password: ""

captive_portal:

uart:
  id: mod_bus
  tx_pin: ${txPin}
  rx_pin: ${rxPin}
  baud_rate: 9600
  stop_bits: 1

modbus:
  send_wait_time: 500ms
  id: mod_bus_siton210

modbus_controller:
  - id: siton210
    address: ${adresa}
    modbus_id: mod_bus_siton210
    command_throttle: 0ms
    setup_priority: -10
    update_interval: ${updates}
    
sensor:
  - platform: modbus_controller
    modbus_controller_id: siton210
    id: napeti
    name: "${node_name} Napětí"
    state_class: measurement
    device_class: voltage
    address: 0x0004
    unit_of_measurement: "V"
    icon: mdi:sine-wave
    #icon: mdi:square-wave
    register_type: holding
    value_type: U_WORD
    accuracy_decimals: 0

  - platform: modbus_controller
    modbus_controller_id: siton210
    id: proud
    name: "${node_name} Proud"
    state_class: measurement
    device_class: current
    address: 0x0005
    unit_of_measurement: "A"
    icon: mdi:pulse
    #icon: mdi:lightning-bolt
    register_type: holding
    value_type: U_WORD
    accuracy_decimals: 2
    filters:
      - multiply: 0.01

  - platform: modbus_controller
    modbus_controller_id: siton210
    id: vykon
    name: "${node_name} Výkon"
    address: 0x0006
    state_class: measurement
    device_class: power
    unit_of_measurement: "W"
    icon: mdi:solar-power
    register_type: holding
    value_type: U_WORD
    accuracy_decimals: 0

  - platform: modbus_controller
    modbus_controller_id: siton210
    id: teplota
    name: "${node_name} Teplota"
    state_class: measurement
    device_class: temperature
    address: 0x0007
    unit_of_measurement: "°C"
    register_type: holding
    value_type: U_WORD
    accuracy_decimals: 0
      
  - platform: modbus_controller
    modbus_controller_id: siton210
    id: vyroba
    name: "${node_name} Výroba kWh"
    state_class: total_increasing
    device_class: energy
    address: 0x000C
    unit_of_measurement: "kWh"
    icon: mdi:chart-bell-curve-cumulative
    register_type: holding
    value_type: U_DWORD_R
    accuracy_decimals: 3
    filters:
      - multiply: 0.001

  - platform: wifi_signal
    name: "${node_name} WiFi Signal"
    entity_category: diagnostic
    disabled_by_default: true

text_sensor:
  - platform: wifi_info
    ip_address:
      name: "${node_name} IP Address"
      entity_category: diagnostic
      disabled_by_default: true
    ssid:
      name: "${node_name} Connected SSID"
      entity_category: diagnostic
      disabled_by_default: true
    bssid:
      name: "${node_name} Connected BSSID"
      entity_category: diagnostic
      disabled_by_default: true
    mac_address:
      name: "${node_name} Mac Wifi Address"
      entity_category: diagnostic
      disabled_by_default: true
    scan_results:
      name: "${node_name} Latest Scan Result"
      entity_category: diagnostic
      disabled_by_default: true
